#!groovy

// Generated by IBM TransformationAdvisor
// Wed Mar 27 14:59:45 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}